### ISSUE TITLE
IllegalArgumentException: north must be in [-85.05112877980658,85.05112877980658]

### ISSUE THREAD

**Issue by mkayander** [mkayander/TouringAndroidApp#9]
Happens most of the time upon configuration update (screen rotation, device waking)

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: net.inqer.touringapp, PID: 23932
    java.lang.IllegalArgumentException: north must be in [-85.05112877980658,85.05112877980658]
        at org.osmdroid.util.BoundingBox.set(BoundingBox.java:74)
        at org.osmdroid.views.Projection.refresh(Projection.java:705)
        at org.osmdroid.views.Projection.<init>(Projection.java:111)
        at org.osmdroid.views.Projection.<init>(Projection.java:123)
        at org.osmdroid.views.MapView.zoomToBoundingBox(MapView.java:558)
        at org.osmdroid.views.MapView.zoomToBoundingBox(MapView.java:584)
        at net.inqer.touringapp.ui.map.MapFragment.setTourWaypointsLine(MapFragment.kt:295)
        at net.inqer.touringapp.ui.map.MapFragment.setTourWaypointsLine(MapFragment.kt:281)
        at net.inqer.touringapp.ui.map.MapFragment.access$setTourWaypointsLine(MapFragment.kt:44)
        at net.inqer.touringapp.ui.map.MapFragment$subscribeObservers$1.onChanged(MapFragment.kt:219)
        at net.inqer.touringapp.ui.map.MapFragment$subscribeObservers$1.onChanged(MapFragment.kt:208)
        at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
        at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:146)
        at androidx.lifecycle.LiveData$ObserverWrapper.activeStateChanged(LiveData.java:468)
        at androidx.lifecycle.LiveData$LifecycleBoundObserver.onStateChanged(LiveData.java:425)
        at androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.java:354)
        at androidx.lifecycle.LifecycleRegistry.forwardPass(LifecycleRegistry.java:265)
        at androidx.lifecycle.LifecycleRegistry.sync(LifecycleRegistry.java:307)
        at androidx.lifecycle.LifecycleRegistry.moveToState(LifecycleRegistry.java:148)
        at androidx.lifecycle.LifecycleRegistry.handleLifecycleEvent(LifecycleRegistry.java:134)
        at androidx.fragment.app.FragmentViewLifecycleOwner.handleLifecycleEvent(FragmentViewLifecycleOwner.java:77)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:3028)
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3126)
        at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3077)
        at androidx.fragment.app.Fragment.performStart(Fragment.java:3030)
        at androidx.fragment.app.FragmentStateManager.start(FragmentStateManager.java:589)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:300)
        at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:112)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1647)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3126)
        at androidx.fragment.app.FragmentManager.dispatchStart(FragmentManager.java:3077)
        at androidx.fragment.app.FragmentController.dispatchStart(FragmentController.java:262)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:510)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1433)
        at android.app.Activity.performStart(Activity.java:7946)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3334)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2046)
        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7564)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
        ```

**Comment by mkayander** [comment]
Failed to commit
